---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: tyatyushkin/ubuntu:focal
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
